### ISSUE TITLE
Get terminal window size

### ISSUE THREAD

**Issue by pcgeek86** [bit101/go-ansi#2]
I can't seem to find a way to retrieve the width and height of the terminal with this package.

For example, let's say that I want to move the cursor to "right side" minus 5 positions. How would I accomplish that?

Another example, how would I specify to move the cursor 2 lines from the bottom of the terminal?

Since I can't get the terminal window size, I can't calculate the offset from the right or bottom sides.

Thanks for any assistance.

**Comment by bit101** [comment]
As far as I know, ansi itself doesn't have any way of querying the width or height of the current terminal. This Stackoverflow question has some good potential workarounds. https://stackoverflow.com/questions/35688348/how-do-i-determine-size-of-ansi-terminal . Seems like the idea is to move the cursor to a high position on x and y and see where it ends up.

Other than that, it seems like you'd need to use system calls, which would differ on platforms. Here's one example of a Go package that does that. https://github.com/kopoli/go-terminal-size . 

I'm probably not going to try to add anything for this use case in this package though.

**Comment by pcgeek86** [comment]
Thank you. I would suggest reconsidering adding it to this package, for simplicity, but it's obviously entirely your choice. Or perhaps there's another Go package that could be used in conjunction. I'll keep searching for something like that. Cheers

**Comment by pcgeek86** [comment]
Here's what I ended up using:
```
go get golang.org/x/term
```

```go
package main
import "golang.org/x/term"

func main() {
  fmt.Println(term.GetSize(0))
}
```

**Comment by bit101** [comment]
Interesting. so `golang.org/x/term` gets the size, which is good because it's part of official packages. Maybe I will look into using that.

**Comment by bit101** [comment]
I added `ansi.TermSize()` using the above. Thanks!
